export { USER_QUERY } from './queries'
export { CREATE_USER_MUTATION } from './mutation'
export { EXERCISES_QUERY } from './queries'
export { UPDATE_COMPLETION } from './mutation'
export { RESET_COMPLETION } from './mutation'
export { CHANGE_STRENGTH } from './mutation'